server:
  port: 8080
spring:
  cloud:
    function:
      definition: testListener
    stream:
      bindings:
        testListener-in-0:
          binder: rabbit
          destination: test
          group: queue.test
      binders:
        rabbit:
          type: rabbit
          enviroment:
            spring:
              rabbitmq:
                password: guest
                username: guest
                port: 5672
                virtual-host: /
                deliveryMode: 2
                host: localhost
      rabbit:
        bindings:
          testListener-in-0:
            consumer:
              queueNAmeGroupOnly: true
              autoBindDlq: true
              bindingRoutingKey: test

